-- Add migration script here
CREATE TABLE M_USER (
    USER_ID         VARCHAR(36) PRIMARY KEY
    , USER_NAME     VARCHAR(165)
    , EMAIL         VARCHAR(255)
    , PASSWORD      VARCHAR(255)
    , SALT          VARCHAR(255)
    , ROLE          VARCHAR(1)
    , STATUS        VARCHAR(1)
    , CREATED_AT    TIMESTAMP
    , UPDATED_AT    TIMESTAMP
    , LAST_LOGIN_AT TIMESTAMP
    , DELETE_FLAG   BOOLEAN
)
;

CREATE TABLE M_PROJECT (
    PROJECT_ID          VARCHAR(36) PRIMARY KEY
    , PROJECT_NAME      VARCHAR(255)
    , DESCRIPTION       TEXT
    , PARENT_PROJECT_ID VARCHAR(36)
    , CREATED_AT        TIMESTAMP
    , UPDATED_AT        TIMESTAMP
    , MANAGER_ID        VARCHAR(36)
)
;

CREATE TABLE M_USER_PROJECT (
    USER_ID      VARCHAR(36)
    , PROJECT_ID VARCHAR(36)
    , ROLE       VARCHAR(1)
    , CREATED_AT TIMESTAMP
    , UPDATED_AT TIMESTAMP
    , PRIMARY KEY (USER_ID, PROJECT_ID)
)
;

CREATE TABLE T_RELATED_TICKET (
    TICKET_ID           INT
    , RELATED_TIKECT_ID INT
    , PRIMARY KEY (TICKET_ID, RELATED_TIKECT_ID)
)
;

CREATE TABLE T_TICKET (
    TICKET_ID             SERIAL PRIMARY KEY
    , TICKET_TITLE        VARCHAR(255)
    , TICKET_TYPE_ID      INT
    , DESCRIPTION         TEXT
    , PRIORITY            INT
    , STATUS_ID           INT
    , PROGRESS            INT
    , START_DATE          DATE
    , DUE_DATE            DATE
    , CREATED_AT          TIMESTAMP
    , UPDATED_AT          TIMESTAMP
    -- 親チケット
    , PARENT_TICKET_ID    INT
    , PROJECT_ID          VARCHAR(36)
    , ASSIGNEE_ID         VARCHAR(36)
)
;

CREATE TABLE M_STATUS_MANAGE (
  STATUS_ID        INT
  , STATUS_NAME    VARCHAR(255)
  , PROJECT_ID     VARCHAR(36)
  , TICKET_TYPE_ID INT
  , PRIMARY KEY (STATUS_ID, TICKET_TYPE_ID)
)
;

CREATE TABLE M_TICKET_TYPE (
  TICKET_TYPE_ID INT
  , TICKET_TYPE_NAME VARCHAR(255)
  , PRIMARY KEY (TICKET_TYPE_ID)
)
;