name: Rust CI

on:
  push:
    branches:
      - main  # 任意のブランチ名に変更

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: chappie
          POSTGRES_PASSWORD: chappie
          POSTGRES_DB: chappie
    
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
    
    - uses: baptiste0928/cargo-install@v2
      name: Install sqlx-cli
      with:
        crate: sqlx-cli

    - name: Set up database
      run: sqlx migrate run

    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ github.job }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-${{ github.job }}-
          ${{ runner.os }}-cargo-
    - name: Build (denying warnings)
      run: cargo build --all-targets --all-features --verbose
    
    - uses: taiki-e/install-action@nextest

    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: nextest
        args: run --all-features --all-targets